// Static lookup lists for the flat single-select fields scattered across the
// ad-creation forms (adsType, contractType, education, brand, etc.) — kept
// separate from the picker component so the data survives independent of
// how it's rendered.
export const optionsTypes = {
  adsType: [{title: 'فروشی'}, {title: 'اجاره ای'}, {title: 'درخواستی'}],
  contractType: [
    {title: 'تمام وقت'},
    {title: 'پاره وقت'},
    {title: 'مشاوره ای'},
    {title: 'پروژه ای'},
  ],
  education: [
    {title: 'زیر دیپلم'},
    {title: 'دیپلم'},
    {title: 'کاردانی'},
    {title: 'کارشناسی'},
    {title: 'کارشناسی ارشد'},
    {title: 'دکتری و بالاتر'},
  ],
  adsCreator: [{title: 'شخصی'}, {title: 'املاک'}],
  suburb: [{title: 'هست'}, {title: 'نیست'}],
  elevator: [{title: 'دارد'}, {title: 'ندارد'}],
  parking: [{title: 'دارد'}, {title: 'ندارد'}],
  floor: [
    {title: 'زیرزمین'},
    {title: 'همکف'},
    {title: 'یک'},
    {title: 'دو'},
    {title: 'سه'},
    {title: 'چهار'},
    {title: 'پنج یا بیشتر'},
  ],
  price: [
    {title: 'قیمت مورد نظر'},
    {title: 'مجانی'},
    {title: 'توافقی (تماس بگیرید)'},
  ],
  brand: [
    {title: 'آیودی'},
    {title: 'آریسان'},
    {title: 'آریو(زوتی)'},
    {title: 'آلفا رومیو'},
    {title: 'اپل'},
    {title: 'ام جی'},
    {title: 'ام وی ام'},
    {title: 'ایسوزو'},
    {title: 'بایک'},
    {title: 'برلیانس'},
    {title: 'بسترن'},
    {title: 'بنز'},
    {title: 'بی ام و'},
    {title: 'بی وای دی'},
    {title: 'پاژن'},
    {title: 'پراید'},
    {title: 'پرتون'},
    {title: 'پژو'},
    {title: 'پورشه'},
    {title: 'پیکان'},
    {title: 'تویوتا'},
    {title: 'تیبا'},
    {title: 'جک'},
    {title: 'جیپ'},
    {title: 'جیلی'},
    {title: 'چانگان'},
    {title: 'چری'},
    {title: 'دانگ فنگ (اچ سی کراس)'},
    {title: 'دنا'},
    {title: 'دوو'},
    {title: 'دی اس'},
    {title: 'رانا'},
    {title: 'رنو'},
    {title: 'سانگ یانگ'},
    {title: 'ساینا'},
    {title: 'سمند'},
    {title: 'سوبارو'},
    {title: 'سوزوکی'},
    {title: 'سیتروین'},
    {title: 'فاو'},
    {title: 'فولکس واگن'},
    {title: 'فیات'},
    {title: 'کاپرا'},
    {title: 'کارا'},
    {title: 'کیا'},
    {title: 'گریت وال'},
    {title: 'لکسوس'},
    {title: 'لند مارک'},
    {title: 'لندور'},
    {title: 'لیفان'},
    {title: 'مازراتی'},
    {title: 'مزدا'},
    {title: 'میتسوبیشی'},
    {title: 'نیسان'},
    {title: 'ولوو'},
    {title: 'هایما'},
    {title: 'هوندا'},
    {title: 'هیوندای'},
    {title: 'دیگر'},
  ],
  chassi: [
    {title: 'سدان(سواری)'},
    {title: 'هاچ بک'},
    {title: 'شاسی بلند'},
    {title: 'وانت'},
    {title: 'ون'},
    {title: 'کوپه/کروک'},
    {title: 'استیشن'},
    {title: 'دیگر'},
  ],
  payType: [{title: 'نقدی'}, {title: 'اقساطی'}],
  carAdsCreator: [{title: 'شخصی'}, {title: 'شرکتی'}],
  image: [{title: 'بله'}, {title: 'خیر'}],
};
